### ISSUE TITLE
Add new payload converter sample using jackson-json-crypto

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/samples-java#229]
Add new sample for encrypting/decrypting json payloads
that uses jackson-json-crypto module

**Comment by mapoulos** [comment]
One thing I noticed: I had very bad performance with the default settings (256 key length). I think it was running the key generation for each decrypt and temporal was complaining about the thread not yielding within a second. Decreasing this down to 128 helped. 

I can add some sample code to the issue next week.

**Comment by tsurdilo** [comment]
@mapoulos thanks for the info!

**Comment by tsurdilo** [comment]
@mapoulos will have to use jackson-json-crypto:1.1.0
cause our samples are built with java 1.8 (jackson-json-crypto after 2.x seems to require java 11) just fyi
