### ISSUE TITLE
Add Authorizer+Claims Mapper sample

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/samples-java#234]
Add Authorizer sample similar to 
https://github.com/temporalio/samples-server/tree/main/extensibility/authorizer

**Comment by tsurdilo** [comment]
will create a demo app instead and video as this would be better suited for that

**Comment by CharlieReitzel** [comment]
Is there a link to the demo app?

**Comment by kutovoy** [comment]
@tsurdilo, @rylandg  could anyone please share a link to the demo app/video? thank you in advance :) This page comes up in google search for authorizer related questions...

**Comment by vikaskumar-yubi** [comment]
Hi @tsurdilo , Curious if Authorizer sample is ready with the link. Looking forward to it
