### ISSUE TITLE
[Feature Request] Sample for Using Local Activity to Notify

### ISSUE THREAD

**Issue by hrishikesh2306** [temporalio/samples-java#304]
### Is your feature request related to a problem? Please describe.
Raising a feature request here as recommeded in https://community.temporal.io/t/signalling-system-human-driven-workflows/160/22?u=hrishikesh_chappadi

This is regarding simulating synchronous updates using local activites.

### Describe the solution you'd like

Please refer to the comment here https://community.temporal.io/t/signalling-system-human-driven-workflows/160/3?u=hrishikesh_chappadi

### Additional context

None.

**Comment by tsurdilo** [comment]
no longer needed, sync update feature is released and we added samples for it for both "core" and "springboot" samples
