### ISSUE TITLE
Redirect url in readme of bookingsaga sample is outdated

### ISSUE THREAD

**Issue by ShubhSingh** [temporalio/samples-java#79]
Hi 

redirect url for unit test in below readme is outdated:
https://github.com/temporalio/samples-java/blob/master/src/main/java/io/temporal/samples/bookingsaga/README.md

Corrected it in below PR:
https://github.com/temporalio/samples-java/pull/78

**Comment by tsurdilo** [comment]
Can be closed - https://github.com/temporalio/samples-java/commit/1949f94fec3cb23815ae21720c33d23f6afb746c
