### ISSUE TITLE
Testing Workflow with mock ChildWorkflow - TestChild

### ISSUE THREAD

**Issue by ansujohn** [temporalio/samples-java#81]
Hi
I am looking at writing test on a Workflow which has ChildWorkflows, mock the ChildWorkflow and test the main workflow.
This sample here is ignored - https://github.com/temporalio/samples-java/blob/master/src/test/java/io/temporal/samples/hello/HelloChildTest.java#L92

Could you please give a sample for the above scenario?

**Comment by GreyTeardrop** [comment]
Hi @ansujohn! There's a pending PR at https://github.com/temporalio/samples-java/pull/73 that switches samples to Mockito 3.x and with that change, the `ChildWorkflows` test can run fine.

CC @mfateev @vitarb

**Comment by ansujohn** [comment]
Thank you
